#if !canImport(ObjectiveC)
import XCTest

extension CodingKeyKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodingKeyKitTests = [
        ("testUniverseWorks", testUniverseWorks),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CodingKeyKitTests.__allTests__CodingKeyKitTests),
    ]
}
#endif
